#include "onix/string.h"

// generated by copilot

char *strcpy(char *dest, const char *src)
{
    char *tmp = dest;
    while ((*dest++ = *src++) != '\0')
        /* nothing */;
    return tmp;
}

char *strcat(char *dest, const char *src)
{
    char *tmp = dest;
    while (*dest)
        dest++;
    while ((*dest++ = *src++) != '\0')
        /* nothing */;
    return tmp;
}

size_t strlen(const char *str)
{
    size_t len = 0;
    while (str[len])
        len++;
    return len;
}

int strcmp(const char *lhs, const char *rhs)
{
    while (*lhs && *rhs && *lhs == *rhs) {
        lhs++;
        rhs++;
    }
    return *lhs - *rhs;
}

char *strchr(const char *str, int ch)
{
    while (*str && *str != ch)
        str++;
    return *str == ch ? (char *)str : NULL;
}

char *strrchr(const char *str, int ch)
{
    char *last = NULL;
    while (*str) {
        if (*str == ch)
            last = (char *)str;
        str++;
    }
    return last;
}

int memcmp(const void *lhs, const void *rhs, size_t n)
{
    const char *l = lhs;
    const char *r = rhs;
    while (n-- > 0) {
        if (*l != *r)
            return *l - *r;
        l++;
        r++;
    }
    return 0;
}

void *memset(void *dest, int ch, size_t n)
{
    char *d = dest;
    while (n-- > 0)
        *d++ = ch;
    return dest;
}

void *memcpy(void *dest, const void *src, size_t n)
{
    char *d = dest;
    const char *s = src;
    while (n-- > 0)
        *d++ = *s++;
    return dest;
}

void *memchr(const void *str, int ch, size_t n)
{
    const char *s = str;
    while (n-- > 0) {
        if (*s == ch)
            return (void *)s;
        s++;
    }
    return NULL;
}
